[project]
name = "google-ads-mcp"
version = "0.1.0"
requires-python = ">=3.10"
license = "Apache-2.0"
dependencies = [
    "google-ads>=31.0.0",
    "mcp[cli]>=1.2.0",
    "fastmcp>=3.2.0"
]

description = "Reliable Google Ads MCP server for ChatGPT."
readme = "README.md"
authors = [{ name = "Boyi Lee" }]
keywords = ["Google Ads", "Google Ads API", "MCP", "ChatGPT"]

[project.optional-dependencies]
dev = [
    "black",
    "pytest"
]

[project.scripts]
google-ads-mcp = "ads_mcp_v2.server:run_server"
